on:
  push:
jobs:
  slack:
    runs-on: ubuntu-latest
    name: slack
    steps:
      - name: Slack Notification
        uses: ry-itto/slack_notify_actions@1.0.1
        env:
          SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/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'
          TITLE: ':tada: Success :tada:'
          BODY: 'ry-itto'
          COLOR: '#4D88C2'
